/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package System;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mahfo
 */
public class Requets extends javax.swing.JFrame {
    Connection con;
    PreparedStatement pst;
    ResultSet rs ;
    /**
     * Creates new form Requets
     */
    public Requets() {
        initComponents();
        listlivres_emprunt ();
        listlivres_disponible ();
        setupTableLivresDispo ();
        setupTableLivresEmp ();
        Liste_abonne();
        setupTableLivresDispo ();
        listlivres_dispo ();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        Titre_em = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        ID_em = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        Titre_di = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2.setText("Livres Empruntés");

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "                                 Livre ID", "                                Livre Titre", "                               Empranteur"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "                                                   Livre ID", "                                                 Livre Titre"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 204));
        jLabel3.setText("Livres Disponibles");

        Titre_em.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Titre_emActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button.png"))); // NOI18N
        jButton1.setText("Rechercher");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ID_em.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_emActionPerformed(evt);
            }
        });

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Livre_ID", "Livre_Titre", "Emprunteur_ID", "Emprunteur_Nom"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button.png"))); // NOI18N
        jButton3.setText("Rechercher");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Titre_di.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Titre_diActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button Abonnés.png"))); // NOI18N
        jButton5.setText("Abonnés");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Emprunt.png"))); // NOI18N
        jButton6.setText("Emprunt");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button Livres.png"))); // NOI18N
        jButton8.setText("Livres");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(ID_em, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Titre_em, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Titre_di, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(67, 67, 67)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ID_em, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Titre_em, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Titre_di, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setBounds(0, 0, 790, 701);
    }// </editor-fold>//GEN-END:initComponents

    private void Titre_emActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Titre_emActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Titre_emActionPerformed

    public void listlivres_dispo (){
            try  {
            Class.forName("com.mysql.cj.jdbc.Driver"); 
            con=DriverManager.getConnection( "jdbc:mysql://localhost:3306/bib","root","");  
            String sql= "select idlivre,titre from livre where disponible = 'OUI'" ;
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
           DefaultTableModel table1 = (DefaultTableModel) jTable2.getModel();
            table1.setRowCount(0);
            while (rs.next()){
               String id_livre = String.valueOf(rs.getInt("idlivre"));
                String Titre = String.valueOf(rs.getString("titre"));
                String tbData [] = {id_livre,Titre};
                table1.addRow(tbData);
            }
            con.close();
        }catch (Exception e) {
            e.printStackTrace();
        }
    
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try  {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection( "jdbc:mysql://localhost:3306/bib","root","");
            String nomabonne = String.valueOf(ID_em.getSelectedItem());
            String sql = "SELECT l.idlivre, l.titre, a.nomab FROM abonne a, livre l WHERE l.idabonne = a.idab and a.nomab = ?  ";
            pst = con.prepareStatement(sql);
            pst.setString(1, nomabonne);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel table1 = (DefaultTableModel) jTable1.getModel();
            table1.setRowCount(0);
            while (rs.next()){
                String idlivre = String.valueOf(rs.getInt("idlivre"));
                String titre = String.valueOf(rs.getString("titre"));
                String nomab = String.valueOf(rs.getString("nomab"));
                String tbData [] = {idlivre,titre,nomab} ;
                table1.addRow(tbData);
            }
            con.close();

            /*con=DriverManager.getConnection( "jdbc:mysql://localhost:3306/bib","root","");
            String titree = String.valueOf(Titre_em.getSelectedItem());
            String sql2 = "SELECT l.idlivre, l.titre, a.nomab FROM abonne a, livre l WHERE l.idabonne = a.idab and l.titre = ?  ";
            pst = con.prepareStatement(sql2);
            pst.setString(1, titree);
            ResultSet rs1 = pst.executeQuery();
            DefaultTableModel table2 = (DefaultTableModel) jTable1.getModel();
            table2.setRowCount(0);
            while (rs1.next()){
                String idlivre1 = String.valueOf(rs1.getInt("idlivre"));
                String titre1 = String.valueOf(rs1.getString("titre"));
                String nomab1 = String.valueOf(rs1.getString("nomab"));
                String tbData [] = {idlivre1,titre1,nomab1} ;
                table2.addRow(tbData);
            }
            con.close();*/

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void ID_emActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_emActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_emActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bib", "root", "");
            String Titre = String.valueOf(Titre_di.getSelectedItem());
            String sql = "SELECT titre FROM livre WHERE titre=? And disponible='OUI';";
            pst = con.prepareStatement(sql);
            pst.setString(1, Titre);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "Le livre est DISPONIBLE.");
            } else {
                JOptionPane.showMessageDialog(null, "Le livre n'est pas DISPONIBLE.");
            }
            rs.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void Titre_diActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Titre_diActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Titre_diActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Er_abonnes ou = new Er_abonnes();
        this.setVisible(false);
        ou.setVisible(true) ;
    }//GEN-LAST:event_jButton5ActionPerformed
                     
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Emprunts ou = new Emprunts();
        this.setVisible(false);
        ou.setVisible(true) ;
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Er_livres ou = new Er_livres();
        this.setVisible(false);
        ou.setVisible(true) ;
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Requets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Requets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Requets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Requets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Requets().setVisible(true);
            }
        });
    }
        /*public void listlivres_emprunt (){
            try  {
            Class.forName("com.mysql.cj.jdbc.Driver"); 
            con=DriverManager.getConnection( "jdbc:mysql://localhost:3306/bib","root","");  
            String sql= "SELECT emprunt.idlivre,abonne.nomab AS author_name, livre.titre AS book_name FROM emprunt JOIN abonne ON emprunt.idab = abonne.idab JOIN livre ON emprunt.idlivre = livre.idlivre" ;
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()){
                String Titre = rs.getString("book_name");
                String ID = rs.getString("idLivre");
                String nomab = rs.getString("author_name");

                ID_em.addItem(ID);
                Titre_em.addItem(Titre);
                Nom_em.addItem(nomab);

            }
            con.close();
        }catch (Exception e) {
            e.printStackTrace();
        }
    
    }*/
    
    public void listlivres_emprunt (){
            try  {
                Titre_em.removeAllItems();
            Class.forName("com.mysql.cj.jdbc.Driver"); 
            con=DriverManager.getConnection( "jdbc:mysql://localhost:3306/bib","root","");  
            String sql= "select titre from livre ;" ;
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()){
                String Titre = rs.getString("titre");
                Titre_em.addItem(Titre);
            }
            con.close();
        }catch (Exception e) {
            e.printStackTrace();
        }
    
    }
  
      public void Liste_abonne(){
            try{
         ID_em.removeAllItems();
        Class.forName("com.mysql.cj.jdbc.Driver"); 
        con=DriverManager.getConnection( "jdbc:mysql://localhost:3306/bib","root",""); 
        String sql= "select nomab from abonne;" ; 
        pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()){
                String Titre = rs.getString("nomab");
                ID_em.addItem(Titre);
            }
            con.close();
            
            }catch (Exception e) {
            e.printStackTrace();
        }
            
            
        }
    
    
    
    
    
  
        public void listlivres_disponible (){
            try  {
            Class.forName("com.mysql.cj.jdbc.Driver"); 
            con=DriverManager.getConnection( "jdbc:mysql://localhost:3306/bib","root","");  
            String sql= "select * from livre" ;
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()){
                String Titre = rs.getString("Titre");
                Titre_di.addItem(Titre);
            }
            con.close();
        }catch (Exception e) {
            e.printStackTrace();
        }
    
    }
        
        public void setupTableLivresEmp () {
     try  {
            Class.forName("com.mysql.cj.jdbc.Driver"); 
            con=DriverManager.getConnection( "jdbc:mysql://localhost:3306/bib","root","");  
            String sql= "select * from livre where disponible = 'NON' " ;
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            DefaultTableModel table1 = (DefaultTableModel) jTable1.getModel();
            table1.setRowCount(0);
            while (rs.next()){
                String id = String.valueOf(rs.getInt("idlivre"));
                String Titre = String.valueOf(rs.getString("Titre"));
                String tbData [] = {id,Titre} ;
                table1.addRow(tbData);    
            }
            con.close();
        }catch (Exception e) {
            e.printStackTrace();
        }
    
    }
        
        
public void setupTableLivresDispo () {
     try  {
            Class.forName("com.mysql.cj.jdbc.Driver"); 
            con=DriverManager.getConnection( "jdbc:mysql://localhost:3306/bib","root","");  
            String sql= "select l.idlivre,l.titre,l.idabonne,a.nomab from livre l , abonne a where l.idabonne=a.idab and l.disponible = 'OUI'" ;
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            DefaultTableModel table1 = (DefaultTableModel) jTable5.getModel();
            table1.setRowCount(0);
            while (rs.next()){
                String id_livre = String.valueOf(rs.getInt("idlivre"));
                String Titre = String.valueOf(rs.getString("titre"));
                String id_abonne = String.valueOf(rs.getInt("idabonne"));
                String nomab = String.valueOf(rs.getString("nomab"));
                String tbData [] = {id_livre,Titre,id_abonne,nomab} ;
                table1.addRow(tbData);    
            }
            con.close();
        }catch (Exception e) {
            e.printStackTrace();
        }
    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ID_em;
    private javax.swing.JComboBox<String> Titre_di;
    private javax.swing.JComboBox<String> Titre_em;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable5;
    // End of variables declaration//GEN-END:variables
}

